Test,Project,Type,Polluter Sequence (OD-Vic) / State-Setter Sequence (OD-Brit) / Conflicting Tests (Concurrency),ID,Commit_Count,Note
aeon/datasets/tests/test_data_writers.py::test_write_to_tsfile_unequal_length[Testy2.ts],aeon,ND,,['7511857043'],1,"Intermittent faliures when reading from / writing to datasets. Circumvented by switching to overnight runs only(commit `68b266909068df1e703d42266b2571d554006741`, squashed into commit `80cfb71b5cbf7a14e14008faddd3ed0722934dd7` when merging `https://github.com/aeon-toolkit/aeon/pull/887`);  Test method renamed to `test_write_to_ts_file_unequal_length` by commit 2fcfe11940a1f8d7a4a3518bf67f82521e63bdee."
aeon/transformations/collection/convolution_based/tests/test_multirocket_m.py::test_multirocket_multivariate_on_basic_motions,aeon,ND,,['7514148037'],1,Flaky due to different possible seeds. Reported by `https://github.com/aeon-toolkit/aeon/issues/1278`. Fixed in commit `502609e4d8f035cfdb156988cdbee6d970c3bec0` (from PR `https://github.com/aeon-toolkit/aeon/pull/1453`)
tests/func/experiments/test_experiments.py::test_modified_data_dep[False-foo: 2-True],dvc,OD-Vic,[tests/func/test_remote.py::test_raise_on_too_many_open_files],['7389433266'],1,
tests/func/experiments/test_experiments.py::test_modified_data_dep[False-foo: 1-True],dvc,OD-Vic,[tests/func/test_remote.py::test_raise_on_too_many_open_files],['7389433266'],1,
tests/func/repro/test_repro.py::test_repro_skip_pull_if_no_run_cache_is_passed,dvc,OD-Vic,[tests/func/test_remote.py::test_raise_on_too_many_open_files],['7389433266'],1,
tests/func/test_checkout.py::test_stats_on_updated_file_from_tracked_dir,dvc,OD-Vic,[tests/func/test_remote.py::test_raise_on_too_many_open_files],['7389433266'],1,
tests/func/test_data_cloud.py::test_pipeline_file_target_ops,dvc,OD-Vic,[tests/func/test_remote.py::test_raise_on_too_many_open_files],['7389433266'],1,
tests/func/test_checkout.py::test_checkout_partial_unchanged,dvc,OD-Vic,[tests/func/test_remote.py::test_raise_on_too_many_open_files],['7389433266'],1,
tests/func/experiments/test_experiments.py::test_modified_data_dep[False-foo: 2-False],dvc,OD-Vic,[tests/func/test_remote.py::test_raise_on_too_many_open_files],['7389433266'],1,
tests/func/test_update.py::test_update_import_url_to_remote_directory,dvc,OD-Vic,[tests/func/test_remote.py::test_raise_on_too_many_open_files],['7389433266'],1,
tests/func/test_add.py::test_should_update_state_entry_for_file_after_add,dvc,OD-Vic,[tests/func/test_remote.py::test_raise_on_too_many_open_files],['7389433266'],1,
tests/func/test_checkout.py::test_checkout_with_relink_existing[hardlink],dvc,OD-Vic,[tests/func/test_remote.py::test_raise_on_too_many_open_files],['7389433266'],1,
tests/func/test_checkout.py::test_checkout_with_relink_existing[copy],dvc,OD-Vic,[tests/func/test_remote.py::test_raise_on_too_many_open_files],['7389433266'],1,
tests/func/experiments/test_experiments.py::test_modified_data_dep[False-foo: 1-False],dvc,OD-Vic,[tests/func/test_remote.py::test_raise_on_too_many_open_files],['7389433266'],1,
tests/func/test_checkout.py::test_checkout_file,dvc,OD-Vic,[tests/func/test_remote.py::test_raise_on_too_many_open_files],['7389433266'],1,
tests/func/test_checkout.py::test_checkout_with_relink_existing[symlink],dvc,OD-Vic,[tests/func/test_remote.py::test_raise_on_too_many_open_files],['7389433266'],1,
IPython/core/tests/test_profile.py::ProfileStartupTest::test_startup_py,ipython,OD-Vic,"[IPython/core/magics/namespace.py::IPython.core.magics.namespace.NamespaceMagics.reset_selective, IPython/core/tests/test_magic.py::test_reset_dhist]",['7461730907'],1,
IPython/core/tests/test_debugger.py::test_xmode_skip,ipython,OD-Vic,"[IPython/core/magics/namespace.py::IPython.core.magics.namespace.NamespaceMagics.reset_selective, IPython/core/tests/test_magic.py::test_reset_dhist]","['7461730907, '7528949484']",2,
IPython/terminal/tests/test_embed.py::test_nest_embed,ipython,OD-Vic,"[IPython/core/magics/namespace.py::IPython.core.magics.namespace.NamespaceMagics.reset_selective, IPython/core/tests/test_magic.py::test_reset_dhist]","['7461730907, '7528949484']",2,
IPython/terminal/tests/test_help.py::test_profile_create_help,ipython,OD-Vic,"[IPython/core/magics/namespace.py::IPython.core.magics.namespace.NamespaceMagics.reset_selective, IPython/core/tests/test_magic.py::test_reset_dhist]",['7528949484'],1,
IPython/core/tests/test_completer.py::TestCompleter::test_completion_have_signature,ipython,OD-Vic,"[IPython/core/tests/test_completer.py::TestCompleter::test_matcher_suppression, IPython/core/tests/test_magic.py::test_rehashx]",['7528756918'],1,
IPython/core/tests/test_shellapp.py::TestFileToRun::test_py_script_file_attribute_interactively,ipython,OD-Vic,"[IPython/core/magics/namespace.py::IPython.core.magics.namespace.NamespaceMagics.reset_selective, IPython/core/tests/test_magic.py::test_reset_dhist]",['7528949484'],1,
IPython/core/tests/test_run.py::TestMagicRunSimple::test_obj_del,ipython,OD-Vic,"[IPython/core/magics/namespace.py::IPython.core.magics.namespace.NamespaceMagics.reset_selective, IPython/core/tests/test_magic.py::test_reset_dhist]","['7461730907', '7528949484']",2,
IPython/core/tests/test_run.py::TestMagicRunSimple::test_tclass,ipython,OD-Vic,"[IPython/core/magics/namespace.py::IPython.core.magics.namespace.NamespaceMagics.reset_selective, IPython/core/tests/test_magic.py::test_reset_dhist]",['7528949484'],1,
IPython/core/tests/test_run.py::test_script_tb,ipython,OD-Vic,"[IPython/core/magics/namespace.py::IPython.core.magics.namespace.NamespaceMagics.reset_selective, IPython/core/tests/test_magic.py::test_reset_dhist]",['7528949484'],1,
IPython/core/tests/test_debugger.py::test_where_erase_value,ipython,OD-Vic,"[IPython/core/magics/namespace.py::IPython.core.magics.namespace.NamespaceMagics.reset_selective, IPython/core/tests/test_magic.py::test_reset_dhist]","['7461730907', '7528949484']",2,
IPython/core/tests/test_shellapp.py::TestFileToRun::test_py_script_file_attribute,ipython,OD-Vic,"[IPython/core/magics/namespace.py::IPython.core.magics.namespace.NamespaceMagics.reset_selective, IPython/core/tests/test_magic.py::test_reset_dhist]","['7528873505', '7528949484']",2,
IPython/core/tests/test_interactiveshell.py::test_run_cell_async,ipython,OD-Vic,[IPython/core/tests/test_interactiveshell.py::InteractiveShellTestCase::test_In_variable],"['7527912524', '7527949834']",2,
IPython/terminal/tests/test_help.py::test_profile_help,ipython,OD-Vic,"[IPython/core/magics/namespace.py::IPython.core.magics.namespace.NamespaceMagics.reset_selective, IPython/core/tests/test_magic.py::test_reset_dhist]",['7528949484'],1,
networkx/algorithms/link_analysis/pagerank_alg.py::networkx.algorithms.link_analysis.pagerank_alg._pagerank_scipy,networkx,ND,,['7561273644'],1,Flaky due to using cached graph from previous calls to `_pagerank_scipy()`. The code changes were discarded by subsequent commit.
networkx/algorithms/community/tests/test_label_propagation.py::TestFastLabelPropagationCommunities::test_random_graph,networkx,ND,,['7377036882'],1,Flaky due to non-determinsitic random number. Resolved via fixed seed by commit 7c0d8812d87c851bc646c1f2739a223885a39b6a (from PR https://github.com/networkx/networkx/pull/7264)
networkx/algorithms/link_analysis/pagerank_alg.py::networkx.algorithms.link_analysis.pagerank_alg.pagerank,networkx,ND,,['7561273644'],1,Flaky due to using cached graph from previous calls to `_pagerank_scipy()`. The code changes were discarded by subsequent commit.
tests/tests_pytorch/models/test_torchscript.py::test_torchscript_input_output[ParityModuleRNN],pytorch-lightning,ND,,['7388565910'],1,"""allclose()"" flaky - marked by commit bf25167bbf64f50ba335aa759318946b21775cd2 ( in PR https://github.com/Lightning-AI/pytorch-lightning/pull/20010)"
tests/test_section.py::SliceTest::test_cap_nohit,trimesh,ND,,['7430287465'],1,"`random_rotation_matrix()` generates numbers without a fixed seed. This can generate ""invalid input geometry"", leading to ""GEOSException: TopologyException: side location conflict at ..."""
